### ISSUE TITLE
Mise a jour de l'acteur LMS

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/plconception#78]
@qcoumes peut tu faire un point sur l'acteur LMS dans https://github.com/PremierLangage/plconception/tree/master/conception/acteurs/LMS.md

Liens vers la documentation  LTI.
Et une description des informations que PL peut remonter vers un LMS 
et une liste des informations que l'on peut récupérer du LMS.
Merci

**Comment by qcoumes** [comment]
Fait !

**Comment by nimdanor** [comment]
Cool
