### ISSUE TITLE
[Spécifications technique] le front 

### ISSUE THREAD

**Issue by nimdanor** [PremierLangage/plconception#92]
@mciissee peut tu faire (pour la semaine prochaine) une demi page pour expliquer les éléments techniques du projet pour l'aspect front dans le document suivant:
https://github.com/PremierLangage/plconception/blob/master/technical/front.md

Quelques lignes pour expliquer l’intérêt d'angular et les liens vers les docs (générales ou spécifique à notre projet) de angular.  

Tu peux reprendre les éléments d'explication que tu a écrit pour le déploiement.

**Comment by mciissee** [comment]
C'est fait
